### PR TITLE
Revert "Fix fetching of ID tokens when using a service account (#487)"

### PR DESCRIPTION
**Pull request by lgruen**

### CODE REVIEW

**Review by MattWellie — APPROVED** [review]
I thought it would be more intuitive to just do a full revert (i.e. back to version 2.32.4, instead of 2.32.4 being the same as 2.32.6)

**Review by illusional — APPROVED** [review]

**Comment by lgruen** [comment]
> I thought it would be more intuitive to just do a full revert (i.e. back to version 2.32.4, instead of 2.32.4 being the same as 2.32.6)

But 2.32.5 has already been released, so we'd need to yank that version?

**Comment by lgruen** [comment]
> But 2.32.5 has already been released, so we'd need to yank that version?

I'm not sure how our automatic analysis-runner "please update" messages would handle that.

**Comment by illusional** [comment]
> I'm not sure how our automatic analysis-runner "please update" messages would handle that.

Not very well: https://github.com/populationgenomics/analysis-runner/blob/43cb4ce72c4a8601846a453a4b8c92821926fe32/analysis_runner/util.py#L147

**Pull request merged**
