### PR TITLE
Dataproc: update Hail version pin to 0.2.95

### PR DESCRIPTION
**Pull request by vladsavelyev**

### CODE REVIEW

**Review by lgruen — APPROVED** [review]

**Comment by lgruen** [comment]
Note that there's been a regression in 0.2.96 for which the fix hasn't been released yet in 0.2.97: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1657511417463239?thread_ts=1657173965.254659&cid=C030X7WGFCL

**Comment by vladsavelyev** [comment]
Oh right, I actually hit this error, but assumed that `densify` didn't work just because my matrix table was split and didn't have LGT firleds. Okay, let's hold until the next version is released.

**Comment by vladsavelyev** [comment]
@lgruen, do you think it's okay to pin to 0.2.95 (while we are waiting for a new version)? It works for me fine.

It also seems that the code that compresses pyfiles is redundant after https://github.com/hail-is/hail/pull/10863

**Comment by lgruen** [comment]
> @lgruen, do you think it's okay to pin to 0.2.95 (while we are waiting for a new version)? It works for me fine.

Sure, sounds good!

**Pull request merged**
