### PR TITLE
Support script with options

### PR DESCRIPTION
**Pull request by vladsaveliev**
E.g. this is how I use it:

```
analysis-runner --dataset tob-wgs --access-level test --output-dir "gs://cpg-tob-wgs-temporary/joint-calling" --description "joint calling" "scripts/batch_workflow.py --callset tob-wgs --version v0 --qc-csv-fname R_210315_BINKAN1_1K1KDNA_M001.csv --keep-scratch --billing-project tob-wgs"
```

### CODE REVIEW

**Comment by lgruen** [comment]
That's odd, I thought this is already working -- at least I've used arguments before.

@illusional Doesn't `click` capture all arguments as a list?

Doesn't it just work if you don't use quotes, like this:
`analysis-runner --dataset tob-wgs --access-level test --output-dir "gs://cpg-tob-wgs-temporary/joint-calling" --description "joint calling" scripts/batch_workflow.py --callset tob-wgs --version v0 --qc-csv-fname R_210315_BINKAN1_1K1KDNA_M001.csv --keep-scratch --billing-project tob-wgs`

**Comment by illusional** [comment]
Yep, [for `nargs=-1`, click captures all arguments as a list](https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments:~:text=If%20it%20is%20set%20to%20%2D1%2C%20then%20an%20unlimited%20number%20of%20arguments%20is%20accepted.): https://github.com/populationgenomics/analysis-runner/blob/6ef1de0544af015b69f7dc74a17ea7648dbbf857/analysis_runner/cli.py#L72

**Review by lgruen — CHANGES_REQUESTED** [review]
See my other comment; sorry, should have used the "submit review" functionality before.

**Comment by vladsaveliev** [comment]
I think for me Click tries to interpret all options first, before building the `nargs=-1` list. So it attempts to parse options to your script like they were options to the analysis-runner cli:

```analysis-runner --dataset tob-wgs --access-level test --output-dir "gs://cpg-tob-wgs-temporary/joint-calling" --description "joint calling" scripts/batch_workflow.py --callset tob-wgs --version v0 --qc-csv-fname R_210315_BINKAN1_1K1KDNA_M001.csv  --keep-scratch --billing-project tob-wgs

Usage: analysis-runner [OPTIONS] [SCRIPT]...
Try 'analysis-runner --help' for help.

Error: no such option: --callset
```

It works though if your script only has positional arguments, but not if there are options that start with dash.

Did it work with options for you too? It's `click==7.1.2` in my environment.

**Review by illusional — APPROVED** [review]

**Pull request merged**
